title = "TG"
baseURL = ""
languageCode = "en-us"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5 

[params]
background_color_class = "bg-black"
# featured_image = "images/DSC09522.jpg"
mainSections = ["posts"]
recent_posts_number = 5

