version: 2

general:
  branches:
    only:
      - source

jobs:
  build:
    docker:
      - image: jguyomard/hugo-builder:latest

    steps:
      - add_ssh_keys:
          fingerprint: 09:50:6a:a2:ef:54:d8:dc:64:93:96:53:d4:4e:f8:83
      - run: git config --global user.email goldschmidt.tina+circleci@gmail.com
      - run: git config --global user.name CircleCI

      - checkout
      - run:
        command: |
          git submodule init
          git submodule update --remote
      - run: .circleci/publish_to_ghpages
      
